#!/usr/bin/env bash
# Creates the Secrets the Helm chart expects. Secrets are never generated by
# the chart itself so that Argo CD does not rotate them on every sync.
#
# Usage:
#   NAMESPACE=voice-avatar-assistant scripts/create-secrets.sh
#
# Every value can be preset through the environment (see the variables below), or put
# in one KEY=value file and passed as SECRETS_FILE=<path> (template: secrets.env.example
# in the repository root). Existing secrets are kept unless FORCE=1 is set (which also
# regenerates every password) or REFRESH lists the secrets to rewrite, for example
# REFRESH=assistant-integrations after changing an API key in the file.
set -euo pipefail

NS="${NAMESPACE:-voice-avatar-assistant}"
if [ -n "${SECRETS_FILE:-}" ]; then
  [ -r "${SECRETS_FILE}" ] || { echo "SECRETS_FILE ${SECRETS_FILE} is not readable"; exit 1; }
  set -a
  # shellcheck disable=SC1090
  . "${SECRETS_FILE}"
  set +a
  echo "loaded ${SECRETS_FILE}"
fi
rand() { openssl rand -hex "${1:-16}"; }

POSTGRES_USER="${POSTGRES_USER:-assistant}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(rand 16)}"
POSTGRES_DB="${POSTGRES_DB:-assistant}"
MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-$(rand 16)}"
N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY:-$(rand 32)}"
LIVEKIT_API_KEY="${LIVEKIT_API_KEY:-APIk$(rand 6)}"
LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET:-$(rand 24)}"
QDRANT_API_KEY="${QDRANT_API_KEY:-$(rand 24)}"

make_secret() {
  local name="$1"; shift
  if oc get secret "${name}" -n "${NS}" >/dev/null 2>&1 && [ "${FORCE:-0}" != "1" ] \
     && ! printf ',%s,' "${REFRESH:-}" | grep -q ",${name},"; then
    echo "keep    ${name} (already exists; REFRESH=${name} rewrites it, FORCE=1 rewrites all)"
    return
  fi
  oc create secret generic "${name}" -n "${NS}" "$@" --dry-run=client -o yaml | oc apply -f - >/dev/null
  echo "created ${name}"
}

oc get namespace "${NS}" >/dev/null

make_secret assistant-postgres \
  --from-literal=POSTGRESQL_USER="${POSTGRES_USER}" \
  --from-literal=POSTGRESQL_PASSWORD="${POSTGRES_PASSWORD}" \
  --from-literal=POSTGRESQL_DATABASE="${POSTGRES_DB}" \
  --from-literal=DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

make_secret assistant-minio \
  --from-literal=MINIO_ROOT_USER="${MINIO_ROOT_USER}" \
  --from-literal=MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD}"

make_secret assistant-n8n \
  --from-literal=N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY}"

# Optional: used when qdrant.apiKeySecret is set in the chart values.
make_secret assistant-qdrant \
  --from-literal=QDRANT_API_KEY="${QDRANT_API_KEY}"

make_secret assistant-livekit \
  --from-literal=LIVEKIT_API_KEY="${LIVEKIT_API_KEY}" \
  --from-literal=LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET}"

# API keys for model endpoints. In-cluster vLLM ignores them; MaaS endpoints need them.
make_secret assistant-models \
  --from-literal=LLM_API_KEY="${LLM_API_KEY:-none}" \
  --from-literal=STT_API_KEY="${STT_API_KEY:-none}" \
  --from-literal=TTS_API_KEY="${TTS_API_KEY:-none}" \
  --from-literal=EMBEDDINGS_API_KEY="${EMBEDDINGS_API_KEY:-none}" \
  --from-literal=GUARDRAILS_API_KEY="${GUARDRAILS_API_KEY:-none}" \
  --from-literal=HF_TOKEN="${HF_TOKEN:-}"

# External integrations. Leave empty to disable a feature.
make_secret assistant-integrations \
  --from-literal=SLACK_BOT_TOKEN="${SLACK_BOT_TOKEN:-}" \
  --from-literal=SIMLI_API_KEY="${SIMLI_API_KEY:-}" \
  --from-literal=SIMLI_FACE_ID="${SIMLI_FACE_ID:-}" \
  --from-literal=TAVUS_API_KEY="${TAVUS_API_KEY:-}" \
  --from-literal=TAVUS_FACE_ID="${TAVUS_FACE_ID:-}" \
  --from-literal=TAVUS_PAL_ID="${TAVUS_PAL_ID:-}" \
  --from-literal=GOOGLE_SERVICE_ACCOUNT_JSON="${GOOGLE_SERVICE_ACCOUNT_JSON:-}" \
  --from-literal=GOOGLE_DOCS_FOLDER_ID="${GOOGLE_DOCS_FOLDER_ID:-}"

echo
echo "Secrets are in namespace ${NS}. Back up assistant-n8n: losing N8N_ENCRYPTION_KEY makes the credentials stored in n8n unreadable."
